/* tslint:disable */
/* eslint-disable */
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.2.0.0 (NJsonSchema v10.1.2.0 (Newtonsoft.Json v11.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------
// ReSharper disable InconsistentNaming

import { mergeMap as _observableMergeMap, catchError as _observableCatch } from 'rxjs/operators';
import { Observable, throwError as _observableThrow, of as _observableOf } from 'rxjs';
import { Injectable, Inject, Optional, InjectionToken } from '@angular/core';
import { HttpClient, HttpHeaders, HttpResponse, HttpResponseBase } from '@angular/common/http';

import * as moment from 'moment';

export const API_BASE_URL = new InjectionToken<string>('API_BASE_URL');

@Injectable()
export class CodingTestServiceProxy {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(API_BASE_URL) baseUrl?: string) {
        this.http = http;
        this.baseUrl = baseUrl ? baseUrl : "https://localhost:5050";
    }

    getTblLeftInfos(): Observable<TblLeftOrRightInfo[]> {
        let url_ = this.baseUrl + "/api/CodingTest/GetTblLeftInfos";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",			
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetTblLeftInfos(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetTblLeftInfos(<any>response_);
                } catch (e) {
                    return <Observable<TblLeftOrRightInfo[]>><any>_observableThrow(e);
                }
            } else
                return <Observable<TblLeftOrRightInfo[]>><any>_observableThrow(response_);
        }));
    }

    protected processGetTblLeftInfos(response: HttpResponseBase): Observable<TblLeftOrRightInfo[]> {
        const status = response.status;
        const responseBlob = 
            response instanceof HttpResponse ? response.body : 
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }};
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(TblLeftOrRightInfo.fromJS(item));
            }
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<TblLeftOrRightInfo[]>(<any>null);
    }

    getTblRightInfos(): Observable<TblLeftOrRightInfo[]> {
        let url_ = this.baseUrl + "/api/CodingTest/GetTblRightInfos";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",			
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetTblRightInfos(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetTblRightInfos(<any>response_);
                } catch (e) {
                    return <Observable<TblLeftOrRightInfo[]>><any>_observableThrow(e);
                }
            } else
                return <Observable<TblLeftOrRightInfo[]>><any>_observableThrow(response_);
        }));
    }

    protected processGetTblRightInfos(response: HttpResponseBase): Observable<TblLeftOrRightInfo[]> {
        const status = response.status;
        const responseBlob = 
            response instanceof HttpResponse ? response.body : 
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }};
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(TblLeftOrRightInfo.fromJS(item));
            }
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<TblLeftOrRightInfo[]>(<any>null);
    }

    pullLeft(tblReposDetailId: number | undefined): Observable<void> {
        let url_ = this.baseUrl + "/api/CodingTest/PullLeft?";
        if (tblReposDetailId === null)
            throw new Error("The parameter 'tblReposDetailId' cannot be null.");
        else if (tblReposDetailId !== undefined)
            url_ += "tblReposDetailId=" + encodeURIComponent("" + tblReposDetailId) + "&"; 
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",			
            headers: new HttpHeaders({
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processPullLeft(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processPullLeft(<any>response_);
                } catch (e) {
                    return <Observable<void>><any>_observableThrow(e);
                }
            } else
                return <Observable<void>><any>_observableThrow(response_);
        }));
    }

    protected processPullLeft(response: HttpResponseBase): Observable<void> {
        const status = response.status;
        const responseBlob = 
            response instanceof HttpResponse ? response.body : 
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }};
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return _observableOf<void>(<any>null);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<void>(<any>null);
    }

    pullRight(tblReposDetailId: number | undefined): Observable<void> {
        let url_ = this.baseUrl + "/api/CodingTest/PullRight?";
        if (tblReposDetailId === null)
            throw new Error("The parameter 'tblReposDetailId' cannot be null.");
        else if (tblReposDetailId !== undefined)
            url_ += "tblReposDetailId=" + encodeURIComponent("" + tblReposDetailId) + "&"; 
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",			
            headers: new HttpHeaders({
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processPullRight(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processPullRight(<any>response_);
                } catch (e) {
                    return <Observable<void>><any>_observableThrow(e);
                }
            } else
                return <Observable<void>><any>_observableThrow(response_);
        }));
    }

    protected processPullRight(response: HttpResponseBase): Observable<void> {
        const status = response.status;
        const responseBlob = 
            response instanceof HttpResponse ? response.body : 
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }};
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return _observableOf<void>(<any>null);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<void>(<any>null);
    }

    syncDataToTblReposDetailFromGithub(): Observable<ReposInfo[]> {
        let url_ = this.baseUrl + "/api/CodingTest/SyncDataToTblReposDetailFromGithub";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",			
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processSyncDataToTblReposDetailFromGithub(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processSyncDataToTblReposDetailFromGithub(<any>response_);
                } catch (e) {
                    return <Observable<ReposInfo[]>><any>_observableThrow(e);
                }
            } else
                return <Observable<ReposInfo[]>><any>_observableThrow(response_);
        }));
    }

    protected processSyncDataToTblReposDetailFromGithub(response: HttpResponseBase): Observable<ReposInfo[]> {
        const status = response.status;
        const responseBlob = 
            response instanceof HttpResponse ? response.body : 
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }};
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(ReposInfo.fromJS(item));
            }
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<ReposInfo[]>(<any>null);
    }
}

export class TblLeftOrRightInfo implements ITblLeftOrRightInfo {
    id!: number;
    tblReposDetailId!: number;
    reposId!: string | undefined;
    reposName!: string | undefined;
    cloneUrl!: string | undefined;
    language!: string | undefined;
    description!: string | undefined;

    constructor(data?: ITblLeftOrRightInfo) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.tblReposDetailId = _data["tblReposDetailId"];
            this.reposId = _data["reposId"];
            this.reposName = _data["reposName"];
            this.cloneUrl = _data["cloneUrl"];
            this.language = _data["language"];
            this.description = _data["description"];
        }
    }

    static fromJS(data: any): TblLeftOrRightInfo {
        data = typeof data === 'object' ? data : {};
        let result = new TblLeftOrRightInfo();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["tblReposDetailId"] = this.tblReposDetailId;
        data["reposId"] = this.reposId;
        data["reposName"] = this.reposName;
        data["cloneUrl"] = this.cloneUrl;
        data["language"] = this.language;
        data["description"] = this.description;
        return data; 
    }
}

export interface ITblLeftOrRightInfo {
    id: number;
    tblReposDetailId: number;
    reposId: string | undefined;
    reposName: string | undefined;
    cloneUrl: string | undefined;
    language: string | undefined;
    description: string | undefined;
}

export class ReposInfo implements IReposInfo {
    id!: string | undefined;
    name!: string | undefined;
    description!: string | undefined;
    clone_Url!: string | undefined;
    language!: string | undefined;

    constructor(data?: IReposInfo) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.name = _data["name"];
            this.description = _data["description"];
            this.clone_Url = _data["clone_Url"];
            this.language = _data["language"];
        }
    }

    static fromJS(data: any): ReposInfo {
        data = typeof data === 'object' ? data : {};
        let result = new ReposInfo();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["name"] = this.name;
        data["description"] = this.description;
        data["clone_Url"] = this.clone_Url;
        data["language"] = this.language;
        return data; 
    }
}

export interface IReposInfo {
    id: string | undefined;
    name: string | undefined;
    description: string | undefined;
    clone_Url: string | undefined;
    language: string | undefined;
}

export class ApiException extends Error {
    message: string;
    status: number; 
    response: string; 
    headers: { [key: string]: any; };
    result: any; 

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): Observable<any> {
    if (result !== null && result !== undefined)
        return _observableThrow(result);
    else
        return _observableThrow(new ApiException(message, status, response, headers, null));
}

function blobToText(blob: any): Observable<string> {
    return new Observable<string>((observer: any) => {
        if (!blob) {
            observer.next("");
            observer.complete();
        } else {
            let reader = new FileReader(); 
            reader.onload = event => { 
                observer.next((<any>event.target).result);
                observer.complete();
            };
            reader.readAsText(blob); 
        }
    });
}